# This Makefile is generated by the made script:
# https://github.com/alx741/made
#
# Replace FILE with your filename
#
# Dependencies:
# 	Pandoc


FILE=post

all: $(FILE).html

$(FILE).html: $(FILE).md
	pandoc $< -o $@

clean:
	rm $(FILE).pdf
